import React, { useMemo, useState } from 'react';
import SlateEditor from './components/SlateEditor/SlateEditor';
import { SAMPLE_DATA } from './constants';
import { transformJsonToSlateNodes } from './utils/slateTransformer';
import { FileJson, RefreshCw } from 'lucide-react';

const App = () => {
  // Transform the data once on mount (or when data changes)
  const initialEditorValue = useMemo(() => {
    return transformJsonToSlateNodes(SAMPLE_DATA);
  }, []);

  const [key, setKey] = useState(0);

  const handleReset = () => {
    setKey(prev => prev + 1); // Force re-mount of editor to reset content
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-blue-600 rounded-lg shadow-lg shadow-blue-600/20">
              <FileJson className="text-white h-5 w-5" />
            </div>
            <div>
                <h1 className="text-lg font-bold text-slate-900 tracking-tight">Requirement Editor</h1>
                <p className="text-xs text-slate-500 font-medium">SlateJS Integration Demo</p>
            </div>
          </div>
          <button 
            onClick={handleReset}
            className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-slate-600 hover:text-blue-600 hover:bg-blue-50 rounded-md transition-all"
          >
            <RefreshCw size={16} />
            Reset Data
          </button>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 h-[calc(100vh-8rem)]">
            {/* Sidebar / Context Info */}
            <div className="hidden lg:block lg:col-span-1 space-y-6">
                <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                    <h3 className="font-semibold text-slate-900 mb-2">About this View</h3>
                    <p className="text-sm text-slate-600 leading-relaxed">
                        This editor visualizes structured data from a JSON source. 
                        The data includes User Stories, Requirements, and Validity scores generated by AI agents.
                    </p>
                </div>

                <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                    <h3 className="font-semibold text-slate-900 mb-4">Structure</h3>
                    <ul className="space-y-3">
                        <li className="flex items-center gap-3 text-sm text-slate-600">
                            <span className="w-2 h-2 rounded-full bg-blue-500"></span>
                            Agent Response Parsing
                        </li>
                        <li className="flex items-center gap-3 text-sm text-slate-600">
                            <span className="w-2 h-2 rounded-full bg-indigo-500"></span>
                            Dynamic Table Generation
                        </li>
                        <li className="flex items-center gap-3 text-sm text-slate-600">
                            <span className="w-2 h-2 rounded-full bg-violet-500"></span>
                            Slate Rich Text Editing
                        </li>
                    </ul>
                </div>
            </div>

            {/* Editor Area */}
            <div className="col-span-1 lg:col-span-3 h-full">
                 {/* Key forces remount to reset initialValue */}
                <SlateEditor key={key} initialValue={initialEditorValue} />
            </div>
        </div>
      </main>
    </div>
  );
};

export default App;
